services:
  project_db:
    image: mysql:5.7
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USER_DB}
      MYSQL_ROOT_PASSWORD: ${PASSWORD_DB}
      MYSQL_PASSWORD: ${PASSWORD_DB}
  app:
    build: .
    command: sh -c "npm run mig:run && npm start"
    ports:
      - "3000:3000"
    depends_on:
      - project_db
    env_file:
      - .env