
services:
  project_db:
    image: mysql:5.7
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: project_db
      MYSQL_USER: 4rl3y
      MYSQL_ROOT_PASSWORD: 53cur3@p455w0rd
      MYSQL_PASSWORD: 53cur3@p455w0rd


      